language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
 - mkdir -p build/logs
 - phpunit -c phpunit.xml.dist

after_script:
 - travis_retry php vendor/bin/php-coveralls